// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsZVlAomWH1K1TvHAezM586Fv2woVNeKQ',
    appId: '1:591774924054:web:938ddfd3f0e89a73d0a437',
    messagingSenderId: '591774924054',
    projectId: 'ar-math-database',
    authDomain: 'ar-math-database.firebaseapp.com',
    storageBucket: 'ar-math-database.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTr1dQ7zhwlGl93WjiM_O0DUV5wFb54Dg',
    appId: '1:591774924054:android:84575a1d8fbffe92d0a437',
    messagingSenderId: '591774924054',
    projectId: 'ar-math-database',
    storageBucket: 'ar-math-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfB9XH5Q8Yd1gPguhxZGCvZnj3u2TX-4Q',
    appId: '1:591774924054:ios:a37481f61ace8870d0a437',
    messagingSenderId: '591774924054',
    projectId: 'ar-math-database',
    storageBucket: 'ar-math-database.firebasestorage.app',
    iosBundleId: 'com.example.geoarappv1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfB9XH5Q8Yd1gPguhxZGCvZnj3u2TX-4Q',
    appId: '1:591774924054:ios:a37481f61ace8870d0a437',
    messagingSenderId: '591774924054',
    projectId: 'ar-math-database',
    storageBucket: 'ar-math-database.firebasestorage.app',
    iosBundleId: 'com.example.geoarappv1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsZVlAomWH1K1TvHAezM586Fv2woVNeKQ',
    appId: '1:591774924054:web:a60ccade53763ee8d0a437',
    messagingSenderId: '591774924054',
    projectId: 'ar-math-database',
    authDomain: 'ar-math-database.firebaseapp.com',
    storageBucket: 'ar-math-database.firebasestorage.app',
  );
}
